spring:
  application:
    name: Claude

  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jackson:
    property-naming-strategy: SNAKE_CASE

  rsocket:
    server:
      port: 19132
      transport: websocket
      mapping-path: /mincraft

server:
  port: 8080

mail:
  sender:
    host: ${MAIL_SENDER_HOST}
    email: ${MAIL_SENDER_EMAIL}
    password: ${MAIL_SENDER_PASSWORD}
    auth: ${MAIL_SENDER_AUTH}
    starttls-required: ${MAIL_SENDER_STARTTLS_REQUIRED}
    starttls-enable: ${MAIL_SENDER_STARTTLS_ENABLE}
    socket-factory-class: ${MAIL_SENDER_SOCKET_CLASS}
    socket-factory-fallback: ${MAIL_SENDER_SOCKET_FALLBACK}
    port: ${MAIL_SENDER_PORT}

app:
  cors:
    allow-hosts: ${ALLOW_HOSTS}
